language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jameem/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jameem/react-test npm run test
